name: Build and Release SIGMArec

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Add version from tag
        run: |
          echo "__version__ = '${{ github.ref_name }}'" > src/__init__.py

      - name: Install PyInstaller
        run: |
          py -m pip install PyInstaller

      - name: Build binary and prepare release
        run: |
          powershell -File .\build.ps1

      - name: Create ZIP archive
        run: powershell Compress-Archive -Path release\* -DestinationPath sigmarec-${{ github.ref_name }}.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: sigmarec-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}